# Generated by Django 2.0.2 on 2018-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp_first', '0002_savedgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgraph',
            name='graphHeight',
            field=models.CharField(default=700, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedgraph',
            name='graphWidth',
            field=models.CharField(default=900, max_length=255),
            preserve_default=False,
        ),
    ]
