# Generated by Django 2.0.2 on 2018-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp_first', '0003_auto_20180401_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgraph',
            name='graphLeft',
            field=models.CharField(default=200, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedgraph',
            name='graphTop',
            field=models.CharField(default=140, max_length=255),
            preserve_default=False,
        ),
    ]
